### ISSUE TITLE
Code for Bayesian analysis table under COM-Poisson model

### ISSUE THREAD

**Issue by wellington36** [maxbiostat/truncation_tests#18]
Testing the codes in this repository (the ones my machine could run), I didn't find any for the table: Bayesian analysis of inventory data (Shmueli et al., 2005) under Conway-Maxwell Poisson model using noisy algorithms:

![image](https://github.com/user-attachments/assets/7c10af6f-560c-44d3-a023-362a196b96a7)

@maxbiostat Would you have the reference for generating this table?

**Comment by wellington36** [comment]
If possible, I'm also having trouble finding the generation code for this table:

![image](https://github.com/user-attachments/assets/258fce5d-f068-4601-ae78-5247c793b36c)

**Comment by maxbiostat** [comment]
All of the code I used for the COMP is [here](https://github.com/maxbiostat/COMP_Stan). Now, there is not single script to generate the MMLE table. I collected the results for each row manually and put them in.
